sudo: required
language: generic
services:
 - docker

before_install:
 - docker build -t regalme/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true regalme/react-test npm test

after_success:
  - docker build -t regalme/multi-client ./client
  - docker build -t regalme/multi-nginx ./nginx
  - docker build -t regalme/multi-server ./server
  - docker build -t regalme/multi-worker ./worker
# next is push up to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push regalme/multi-client
  - docker push regalme/multi-server
  - docker push regalme/multi-nginx
  - docker push regalme/multi-worker
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-848684029682'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY